config/routes.rb
Rails.application.routes.draw do

  root(to: "home#index")

  get('score', to: 'score#index')

  devise_for(:users, path_prefix: 'p')
  as(:user) do
    get('p/users/edit' => 'devise/registrations#edit', as: 'edit_user_registration')
    put('p/users' => 'devise/registrations#update', as: 'user_registration')
  end

  concern(:paginatable) do
    get('(page/:page)', action: :index, on: :collection, as: '')
  end

  resources(:users, concerns: :paginatable)
  resources(:judgements, concerns: :paginatable)
  resources(:answers, concerns: :paginatable)
  resources(:quizzes, concerns: :paginatable)
  resources(:chapters, concerns: :paginatable)

end

app/models/judgement.rb
class Judgement < ActiveRecord::Base
  # Relationship
  belongs_to(:answer)
  belongs_to(:user)

  # Enum
  enum(result: [ :reject, :pass ])

  # HasScope Gem: resources filter
  # Ref: https://github.com/plataformatec/has_scope
  scope(:chapter, -> chapter { joins(answer: :quiz).where(quizzes: {chapter_id: chapter}) })
  scope(:quiz, -> quiz { joins(:answer).where(answers: {quiz_id: quiz}) })
  scope(:examinee, -> examinee { joins(:answer).where(answers:{ user_id: examinee}) })
  scope(:reviewer, -> reviewer { where(user_id: reviewer) })
  scope(:result, -> result { where(result: result) })
  scope(:passed, -> { where(result: Judgement.results[:pass]) })
  scope(:rejected, -> { where(result: Judgement.results[:reject]) })
  scope(:period_from, -> period_from { where("? <= created_at ", period_from) })
  scope(:period_end, -> period_end { where("created_at <= ?", period_end) })
  scope(:answer, -> key_word { search_answer(key_word) })
  scope(:judgement, -> key_word { search(key_word) })

  # 萃取今天提交的裁決
  def self.today
    where("judgements.created_at >= ?", Time.zone.now.beginning_of_day)
  end

  # 萃取內文有指定關鍵字的裁決
  # Arel's ref: https://github.com/rails/arel
  def self.search(key_word)
    Judgement.select(Judgement.arel_table[Arel.star]).where(Judgement.arel_table[:content].matches("%#{key_word}%"))
  end

  # 萃取所屬解答的內文有指定關鍵字的裁決
  # Arel's and arel_table's ref: https://github.com/rails/arel
  def self.search_answer(key_word)
    Judgement.select(Judgement.arel_table[Arel.star]).where(Answer.arel_table[:content].matches("%#{key_word}%")).joins(
      Judgement.arel_table.join(Answer.arel_table).on(
        Answer.arel_table[:id].eq(Judgement.arel_table[:answer_id])
      ).join_sources
    )
  end
end

app/controllers/judgements_controller.rb
class JudgementsController < ApplicationController

  # 在指定的方法執行前，先設置相關的實例變數，以省略冗贅的敘述
  before_action(:set_judgement, only: [:show, :edit, :update, :destroy])

  # Authorizing controller actions
  # Ref: https://github.com/ryanb/cancan/wiki/authorizing-controller-actions
  authorize_resource

  # HasScope Gem: resources filter
  # Ref: https://github.com/plataformatec/has_scope
  has_scope(:chapter)
  has_scope(:quiz)
  has_scope(:examinee)
  has_scope(:reviewer)
  has_scope(:result)
  has_scope(:passed, type: :boolean)
  has_scope(:rejected, type: :boolean)
  has_scope(:period_from)
  has_scope(:period_end)
  has_scope(:answer)
  has_scope(:judgement)

  # GET /judgements
  def index
    @judgements = apply_scopes(Judgement).order('created_at DESC').all.page(params[:page]).per(50)
    @reviewers = Judgement.includes(:user).group(:user_id).order('COUNT(*) DESC').map(&:user)
  end

  # GET /judgements/1
  def show
  end

  # GET /judgements/new
  def new
    answer = Answer.find(params[:target])
    unless answer
      return render(:wrong_target)
    end

    if answer.done?
      return redirect_to(answers_url, alert: 'The answer has been judged.')
    end

    answer.judging!
    @judgement = Judgement.new
    @judgement.answer = answer
  end

  # GET /judgements/1/edit
  def edit
    authorize!(:update, @judgement)
  end

  # POST /judgements
  def create
    @judgement = Judgement.new(judgement_params)
    @judgement.user = current_user if cannot?(:manage, Answer)
    authorize!(:create, @judgement)

    if params[:cancel]
      @judgement.answer.queue!
      return redirect_to(answers_url, alert: 'Judgement canceled! Answer return to queue.')
    end

    if @judgement.save
      @judgement.answer.done!
      rejudge_grid
      return redirect_to(answers_url, notice: 'Judgement was successfully created.')
    end

    render(:new)
  end

  # PATCH/PUT /judgements/1
  def update
    authorize!(:update, @judgement)

    @judgement.user = current_user if cannot?(:manage, Answer)

    if @judgement.update(judgement_params)
      @judgement.answer.done!
      rejudge_grid
      return redirect_to(judgements_url, notice: 'Judgement was successfully updated.')
    end

    render(:edit, local: {judgement: @judgement})
  end

  # DELETE /judgements/1
  def destroy
    authorize!(:destroy, @judgement)

    @judgement.answer.queue!
    @judgement.destroy
    rejudge_grid

    redirect_to(judgements_url, notice: 'Judgement was successfully destroyed.')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_judgement
    @judgement = Judgement.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def judgement_params
    params.require(:judgement).permit(:answer_id, :user_id, :content, :result, :cancel)
  end

  # 重新判定該判定所屬的九宮格的通過狀態
  def rejudge_grid
    answer = @judgement.answer
    grid = @judgement.answer.quiz.chapter.grids.where(user: answer.user).first
    grid.update_status
  end
end

app/helpers/judgements_helper.rb
module JudgementsHelper
end

app/views/judgements/_form.html.erb
  <% if @judgement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@judgement.errors.count, "error") %> prohibited this judgement from being saved:</h2>

      <ul>
      <% @judgement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <h5 class="ui blue top attached header">
      <%= @judgement.answer.quiz.chapter.number %> - <%= @judgement.answer.quiz.title %>
    </h5>
    <div class="ui bottom attached segment">
      <%= markdown_render(@judgement.answer.quiz.content) %>
    </div>
    <% @judgement.answer.get_answers_history.each do | log | %>
      <h5 class="ui red top attached header">
        Log #<%= log.id %> - <%= log.judgement.result %>
      </h5>
      <div class="ui attached segment">
        <% if params[:ans_format] == 'text' %>
          <code style="color: black; font-size: 1em; background-color: white;">
            <%= simple_format(log.content) %>
          </code>
        <% else %>
          <%= markdown_render(log.content) %>
        <% end %>
        <p style="text-align:right;">
          <%= time_tag(log.created_at) %>
        </p>
      </div>
      <div class="ui bottom attached segment">
        <%= markdown_render(log.judgement.content) %>
        <p style="text-align:right;">
          ——
          <%= log.judgement.user.username %>
          (<%= log.judgement.user.realname %>)
        </p>
      </div>
    <% end %>

    <h5 class="ui orange top attached header">
      Latest Answer
    </h5>
    <div class="ui bottom attached segment">
      <% if params[:ans_format] == 'text' %>
        <code style="color: black; font-size: 1em; background-color: white;">
          <%= simple_format(@judgement.answer.content) %>
        </code>
      <% else %>
        <%= markdown_render(@judgement.answer.content) %>
      <% end %>
      <p style="text-align:right;">
        ——
        <%= @judgement.answer.user.realname %>
        (<%= @judgement.answer.user.username %>)
      </p>
    </div>
    <% if params[:ans_format] == 'text' %>
      <%= link_to(url_for(target: params[:target])) do %>
        <div class="fluid ui yellow basic button">Change answer render to Markdown</div>
      <% end %>
    <% else %>
      <%= link_to(url_for(target: params[:target] ,ans_format: 'text')) do %>
        <div class="fluid ui yellow basic button">Change answer render to Text</div>
      <% end %>
    <% end %>
    <h5 class="ui green top attached header">
      Reference
    </h5>
    <div class="ui bottom attached segment">
      <%= markdown_render(@judgement.answer.quiz.reference) %>
    </div>
  </div>

<div style="margin: 1em 0"/>

<%= form_for(@judgement, html: { class: "ui large form" }) do |f| %>
  <% if can?(:manage, Judgement) %>
    <div class="field">
      <%= f.label(:answer_id) %>
      <%= f.text_field(:answer_id, value: @judgement.answer.id) %>
    </div>
    <div class="field">
      <%= f.label(:reviewers) %>
      <%= f.text_field(:user_id, value: current_user.id) %>
    </div>
  <% else %>
    <%= f.hidden_field(:answer_id, value: @judgement.answer.id) %>
  <% end %>

  <div class="field">
    <%= f.label(:content) %>
    <%= f.text_area(:content) %>
  </div>

  <div class="grouped fields">
    <%= f.label(:result) %>
    <div class="field">
      <div class="ui radio checkbox">
        <%= f.radio_button(:result, :pass) %>
        <%= f.label(:result, :pass, value: :pass) %>
      </div>
    </div>
    <div class="field">
      <div class="ui radio checkbox">
        <%= f.radio_button(:result, :reject) %>
        <%= f.label(:result, :reject, value: :reject) %>
      </div>
    </div>
  </div>
  <div class="field">
    Editor have supported
    <a href="http://markdown.tw/" target="_blank">Markdown markup</a>
    and most of
    <a href="https://help.github.com/articles/github-flavored-markdown/" target="_blank">GitHub Flavored Markdown</a>.
    Try to use it! =D
  </div>
  <%= f.button(class: "ui blue button") %>
  <%= f.button("Cancel", name: "cancel", class: "ui button") %>
<% end %>

app/views/judgements/edit.html.erb
<h2>Editing judgement</h2>

<%= render('form') %>

app/views/judgements/index.html.erb
<h2 class="ui dividing header">Listing judgements</h2>
<div class="ui styled accordion" style="width: 100%">
  <div class="title">
    <i class="dropdown icon"></i>
    Filter & Search
  </div>
  <div class="content">
    <%= form_tag(judgements_path, method: 'get', class: "ui small form") do %>
    <div class="six fields">
      <div class="field">
        <label>Chapter ID</label>
        <input type="text" name="chapter" placeholder="Chapter ID">
      </div>
      <div class="field">
        <label>Quiz ID</label>
        <input type="text" name="quiz" placeholder="Quiz ID">
      </div>
      <div class="field">
        <label>Examinee ID</label>
        <input type="text" name="examinee" placeholder="Examinee ID">
      </div>
      <div class="field">
        <label>Reviewer ID</label>
        <input type="text" name="reviewer" placeholder="Reviewer ID">
      </div>
      <div class="field">
        <label>Result</label>
        <select name="result" class="ui dropdown">
          <option value="">Result</option>
          <option value="<%= Judgement.results[:pass] %>">Pass</option>
          <option value="<%= Judgement.results[:reject] %>">Reject</option>
        </select>
      </div>
    </div>
    <div class="ui divider"></div>
    <div class="four fields">
      <div class="field">
        <label>Search Answer</label>
        <input type="text" name="answer" placeholder="Key word(s)">
      </div>
      <div class="field">
        <label>Search Judgement</label>
        <input type="text" name="judgement" placeholder="Key word(s)">
      </div>
      <div class="field">
        <label>Period From</label>
        <input type="date" name="period_from">
      </div>
      <div class="field">
        <label>Period End</label>
        <input type="date" name="period_end">
      </div>
    </div>
    <%= button_tag("Filt", class: "ui blue button") %>
    <% end %>
  </div>
</div>

<div class="ui hidden divider"></div>

<div class="ui centered grid">
  <div class="sixteen wide column">
    <h5 class="ui top attached center aligned blue header">
      Reviewers Judgement Rank!
    </h5>
    <div class="ui attached blue segment">
      <div class="ui tiny statistics">
        <% @reviewers.each do |reviewer| %>
          <div class="statistic" style="margin-bottom: 0;">
            <div class="value">
              <%= reviewer.judgements.count %>
            </div>
            <div class="label">
              <%= reviewer.username %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<table class="ui table">
  <thead>
    <tr>
      <th>#</th>
      <th>Examinee</th>
      <th>CH</th>
      <th>Quiz</th>
      <th>Result</th>
      <th>Reviewers</th>
      <th>Updated At</th>
    </tr>
  </thead>

  <tbody>
    <% @judgements.each do |judgement| %>
      <tr>
        <td>
          <%= link_to(judgement.id, judgement) %>
        </td>
        <td>
          <%= link_to(judgement.answer.user, style: "color:rgba(0, 0, 0, 0.8);") do %>
            <%= judgement.answer.user.realname %>
            (<%= judgement.answer.user.username %>)
          <% end %>
        </td>
        <td>
          <%= link_to(chapter_path(judgement.answer.quiz.chapter), style: "color:rgba(0, 0, 0, 0.8);") do %>
            <%= judgement.answer.quiz.chapter.number %>
          <% end %>
        </td>
        <td>
          <%= link_to(quiz_path(judgement.answer.quiz), style: "color:rgba(76, 0, 0, 0.8);") do %>
            <% if judgement.answer.quiz.title.length >= 35 %>
              <%= word_wrap(judgement.answer.quiz.title, line_width: 35)[/.+\n/]  %>...
            <% else %>
              <%= judgement.answer.quiz.title %>
            <% end %>
            (#<%= judgement.answer.quiz.id %>)
          <% end %>
        </td>
        <td>
          <% if judgement.user_id == current_user.id %>
            <%= link_to(edit_judgement_path(judgement)) do%>
              <%= puts_answer_label(judgement.answer) %>
            <% end %>
          <% else %>
            <%= link_to(judgement_path(judgement)) do%>
              <%= puts_answer_label(judgement.answer) %>
            <% end %>
          <% end %>
        </td>
        <td>
          <%= link_to(judgement.user, style: "color:rgba(0, 0, 0, 0.8);") do %>
            <%= judgement.user.username %>
          <% end %>

        </td>
        <td>
          <% if judgement.updated_at > 7.day.ago %>
            <%= distance_of_time_in_words_to_now(judgement.updated_at) %> ago
          <% else %>
            <%= time_tag(judgement.updated_at) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="ui column centered grid" style="margin-top:1em;">
  <%= paginate(@judgements, window: 2, outer_window: 1) %>
</div>

app/views/judgements/new.html.erb
<h1>New judgement</h1>
<%= render('form') %>

app/views/judgements/show.html.erb
<h2 class="ui dividing header">Judgement</h2>
<p id="notice"><%= notice %></p>

<div>
  <h5 class="ui blue top attached header">
    <%= @judgement.answer.quiz.chapter.number %> - <%= @judgement.answer.quiz.title %>
  </h5>
  <div class="ui bottom attached segment">
    <%= markdown_render(@judgement.answer.quiz.content) %>
  </div>

  <h5 class="ui green top attached header">
    Reference
  </h5>
  <div class="ui bottom attached segment">
    <%= markdown_render(@judgement.answer.quiz.reference) %>
  </div>

  <h5 class="ui orange top attached header">
    Answer
    <%= puts_answer_label(@judgement.answer) %>
  </h5>
  <div class="ui attached segment">
    <% if params[:ans_format] == 'text' %>
      <code style="color: black; font-size: 1em; background-color: white;">
        <%= simple_format(@judgement.answer.content) %>
      </code>
    <% else %>
      <%= markdown_render(@judgement.answer.content) %>
    <% end %>
    <p style="text-align:right;">
      ——
      <%= @judgement.answer.user.realname %>
      (<%= @judgement.answer.user.username %>)
    </p>
  </div>
  <div class="ui bottom attached segment">
    <%= markdown_render(@judgement.content) %>
    <p style="text-align:right;">
      ——
      <%= @judgement.user.username %>
      (<%= @judgement.user.realname %>)
    </p>
  </div>

  <% if params[:ans_format] == 'text' %>
    <%= link_to(url_for(target: params[:target])) do %>
      <div class="fluid ui yellow basic button">Change answer render to Markdown</div>
    <% end %>
  <% else %>
    <%= link_to(url_for(target: params[:target] ,ans_format: 'text')) do %>
      <div class="fluid ui yellow basic button">Change answer render to Text</div>
    <% end %>
  <% end %>
</div>

<div class="ui hidden divider"></div>

<% if can?(:update, @judgement) %>
  <%= link_to(edit_judgement_path(@judgement)) do %>
    <div class="ui blue button">Rejudge</div>
  <% end %>
<% end %>
<%= link_to(judgements_path) do %>
  <div class="ui basic button">Back to list</div>
<% end %>
<%= link_to(answers_path) do %>
  <div class="ui basic button">Back to answers</div>
<% end %>
<% if can?(:destroy, @judgement) %>
  <%= link_to(@judgement, method: :delete, data: { confirm: "It will be destroy and requeue answer.\nAre you sure?" }) do %>
    <div class="ui button">Destroy</div>
  <% end %>
<% end %>

app/views/judgements/wrong_target.html.erb
<h1>New judgement</h1>
<p>You have a wrong answer target, please go back to answer list and rechoose.</p>
<%= link_to('Back to answers', answers_path) %> |