config/routes.rb
Rails.application.routes.draw do

  root(to: "home#index")

  get('score', to: 'score#index')

  devise_for(:users, path_prefix: 'p')
  as(:user) do
    get('p/users/edit' => 'devise/registrations#edit', as: 'edit_user_registration')
    put('p/users' => 'devise/registrations#update', as: 'user_registration')
  end

  concern(:paginatable) do
    get('(page/:page)', action: :index, on: :collection, as: '')
  end

  resources(:users, concerns: :paginatable)
  resources(:judgements, concerns: :paginatable)
  resources(:answers, concerns: :paginatable)
  resources(:quizzes, concerns: :paginatable)
  resources(:chapters, concerns: :paginatable)

end

app/models/answer.rb
class Answer < ActiveRecord::Base

  # Relationship
  belongs_to(:quiz)
  belongs_to(:user)
  has_one(:judgement)

  # Enum
  enum(status: [:queue, :judging, :done])

  # 檢查指定欄位不為 nil 或空字串
  validates_presence_of(:content, :user_id)

  # HasScope Gem: resources filter
  # Ref: https://github.com/plataformatec/has_scope
  scope(:chapter, -> chapter { joins(:quiz).where(quizzes: {chapter_id: chapter}) })
  scope(:quiz, -> quiz { where(quiz_id: quiz) })
  scope(:examinee, -> examinee { where(user_id: examinee) })
  scope(:status, -> status { where(status: status) })
  scope(:period_from, -> period_from { where("? <= created_at ", period_from) })
  scope(:period_end, -> period_end { where("created_at <= ?", period_end) })
  scope(:answer, -> key_word { search_answer(key_word) })

  # 助教觀看答題清單的優先順序演算法
  # 1. 沒通過該章節的優先於通過該章節的
  # 2. 當天提交次數少得優先於提交次數多的
  # 3. 先提交的優先於晚提交的
  def self.judge_piority
    select("answers.*, grids.status as grid_status, counter.count")
    .joins(:quiz, user: :grids)
    .joins("LEFT OUTER JOIN (" +
           " SELECT `user_id`, COUNT(user_id) as `count` FROM `answers`" +
           " WHERE `status` = 2 AND `created_at` >= '#{Time.now.beginning_of_day.getutc}'" +
           " GROUP BY `user_id`) as `counter`" +
           " ON `answers`.`user_id` = `counter`.`user_id`") # Need to refactor with activerecord
    .where("grids.chapter_id = quizzes.chapter_id")
    .order("grid_status ASC") # Not pass is higher than passed
    .order("count ASC")       # Judged answer less one is higher than more one (MYSQL only)
    .order("created_at ASC")  # Ealier submit is higher than later one
  end

  # 萃取今天提交的答案
  def self.today
    where("answers.created_at >= ?", Time.zone.now.beginning_of_day)
  end

  def get_answers_history
    quiz.get_answer_logs_by_user(user_id)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  # 在指定的方法執行前，先設置相關的實例變數，以省略冗贅的敘述
  before_action(:set_answer, only: [:show, :edit, :update, :destroy])

  # Authorizing controller actions
  # Ref: https://github.com/ryanb/cancan/wiki/authorizing-controller-actions
  authorize_resource

  # HasScope Gem: resources filter
  # Ref: https://github.com/plataformatec/has_scope
  has_scope(:chapter)
  has_scope(:quiz)
  has_scope(:examinee)
  has_scope(:status)
  has_scope(:period_from)
  has_scope(:period_end)
  has_scope(:answer)

  def index
    if can?(:create, Judgement)
      status = [Answer.statuses[:queue], Answer.statuses[:judging]]
      answers = apply_scopes(Answer).where(status: status).judge_piority
    else
      answers = Answer.where(user_id: current_user.id).order("created_at DESC")
    end
    @answers = answers.page(params[:page]).per(50)
  end

  # GET /answers/1
  def show; end

  # GET /answers/new
  def new
    unless Quiz.exists?(id: params[:target])
      return redirect_to(answers_url)
    end
    @answer = Answer.new
    @answer.quiz = Quiz.find(params[:target])
  end

  # POST /answers
  def create
    @answer = Answer.new(answer_params)
    @answer.user_id = current_user.id if cannot?(:manage, Answer)
    authorize!(:create, @answer)
    if params[:preview]
      @preview = true
      return render(:new)
    end

    if @answer.save
      @answer.queue!
      return redirect_to(@answer.quiz.chapter, notice: 'Answer was successfully created.')
    end

    render(:new)
  end

  # GET /answers/1/edit
  def edit; end

  # PATCH/PUT /answers/1
  def update
    if @answer.update(answer_params)
      return redirect_to(@answer, notice: 'Answer was successfully updated.')
    end

    render(:edit)
  end

  # DELETE /answers/1
  def destroy
    @answer.destroy
    redirect_to(answers_url, notice: 'Answer was successfully destroyed.')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_answer
    @answer = Answer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def answer_params
    params.require(:answer).permit(:user_id, :quiz_id, :content)
  end

  # 取得解答的統計數據
  helper_method def get_answers_statistics
    {
      all:    {color: :blue,    value: Answer.count             },
      judged: {color: :purple,  value: Judgement.count          },
      pass:   {color: :green,   value: Judgement.passed.count   },
      reject: {color: :red,     value: Judgement.rejected.count }
    }
  end

  # 取得僅限於今日解答的統計數據
  helper_method def get_answers_statistics_today
    {
        all:    {color: :blue,    value: Answer.today.count             },
        judged: {color: :purple,  value: Judgement.today.count          },
        pass:   {color: :green,   value: Judgement.passed.today.count   },
        reject: {color: :red,     value: Judgement.rejected.today.count }
    }
  end

  # 取得解答的統計數據
  helper_method def get_queue_answers_count
    Answer.where(status: Answer.statuses[:queue]).count
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer, html: { class: "ui form" }) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @answer.quiz %>
    <%= f.hidden_field(:quiz_id, value: @answer.quiz.id) %>
  <% end %>

  <% if can?(:manage, Answer) %>
    <div class="field">
      <%= f.label(:user_id) %>
      <%= f.text_field(:user_id) %>
    </div>
    <div class="field">
      <%= f.label(:quiz_id) %>
      <%= f.text_field(:quiz_id) %>
    </div>
  <% end %>

  <% if can?(:manage, Answer) || can?(:create, @answer) %>
    <div class="field">
      <%= f.text_area(:content) %>
    </div>
    <div class="field">
      Editor have supported
      <a href="http://markdown.tw/" target="_blank">Markdown markup</a>
      and most of
      <a href="https://help.github.com/articles/github-flavored-markdown/" target="_blank">GitHub Flavored Markdown</a>.
      Try to use it! =D
    </div>
    <%= f.button(class: "ui blue button") %>
    <%= button_tag("Preview", name: :preview, value: true, class: "ui orange button") %>
  <% else %>
    <p> You have to go to Chapter page and choose quiz from grid </p>
  <% end %>
  <% if @answer.quiz %>
    <%= link_to(quiz_path(@answer.quiz)) do %>
      <div class="ui button">Cancel and back to quiz</div>
    <% end %>
  <% end %>

<% end %>

app/views/answers/edit.html.erb
<h2 class="ui dividing header">Editing answer</h2>

<%= render('form') %>

app/views/answers/index.html.erb
<h2 class="ui dividing header">Listing answers</h2>

<% if can?(:create, Judgement) %>
  <div class="ui styled accordion" style="width: 100%">
    <div class="title">
      <i class="dropdown icon"></i>
      Filter & Search
    </div>
    <div class="content">
      <%= form_tag(answers_path, :method => 'get', class: "ui small form") do %>
      <div class="four fields">
        <div class="field">
          <label>Chapter ID</label>
          <input type="text" name="chapter" placeholder="Chapter ID">
        </div>
        <div class="field">
          <label>Quiz ID</label>
          <input type="text" name="quiz" placeholder="Quiz ID">
        </div>
        <div class="field">
          <label>Examinee ID</label>
          <input type="text" name="examinee" placeholder="Examinee ID">
        </div>
        <div class="field">
          <label>State</label>
          <select name="status" class="ui dropdown">
            <option value="">State</option>
            <option value="<%= Answer.statuses[:queue] %>">Queue</option>
            <option value="<%= Answer.statuses[:judging] %>">Judgement</option>
          </select>
        </div>
      </div>
      <div class="ui divider"></div>
      <div class="four fields">
        <div class="field">
          <label>Search Answer</label>
          <input type="text" name="answer" placeholder="Key word(s)">
        </div>
        <div class="field">
          <label>Period From</label>
          <input type="date" name="period_from">
        </div>
        <div class="field">
          <label>Period End</label>
          <input type="date" name="period_end">
        </div>
      </div>
      <%= button_tag("Filt", class: "ui blue button") %>
      <% end %>
    </div>
  </div>
  <div class="ui hidden divider"></div>
<% end %>

<% if can?(:create, Judgement) %>
  <div class="ui centered grid">
    <div class="six wide column">
      <h5 class="ui top attached center aligned blue header">
        Today
      </h5>
      <div class="ui attached blue segment">
        <div class="ui tiny statistics">
          <% get_answers_statistics_today.each do | index, properties | %>
            <div class="<%= properties[:color] %> statistic" style="margin-bottom: 0; width: 49px;">
              <div class="value">
                <%= properties[:value] %>
              </div>
              <div class="label">
                <%= "#{index}".humanize.upcase %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="two wide column">
      <h5 class="ui top attached center aligned yellow header">
        Queue
      </h5>
      <div class="ui attached yellow segment">
        <div class="ui tiny statistics">
          <div class="yellow statistic" style="margin-bottom: 0; width: 57px;">
            <div class="value">
              <%= get_queue_answers_count %>
            </div>
            <div class="label">
              Queue
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="eight wide column">
      <h5 class="ui top attached center aligned purple header">
        All
      </h5>
      <div class="ui attached purple segment">
        <div class="ui tiny statistics">
          <% get_answers_statistics.each do | index, properties | %>
            <div class="<%= properties[:color] %> statistic" style="margin-bottom: 0; width: 73px;">
              <div class="value">
                <%= properties[:value] %>
              </div>
              <div class="label">
                <%= "#{index}".humanize.upcase %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>


<table class="ui table">
  <thead>
    <tr>
      <th>#</th>
      <% if can?(:create, Judgement) %>
        <th>Examinee</th>
      <% end %>
      <th>CH</th>
      <th>Quiz</th>
      <th>State</th>
      <th>Created At</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td>
          <%= link_to(answer.id, answer) %>
        </td>
        <% if can?(:create, Judgement) %>
          <td>
            <%= link_to(answer.user, style: "color:rgba(0, 0, 0, 0.8);")  do %>
              <%= answer.user.realname %>
              (<%= answer.user.username %>)
            <% end %>
            <% if !answer.count.nil? %>
              <span style="color: #00b5ad!important;" >[<%= answer.count %>]</span>
            <% end %>
          </td>
        <% end %>
        <td>
          <%= link_to(chapter_path(answer.quiz.chapter), style: "color:rgba(0, 0, 0, 0.8);")  do %>
            <%= answer.quiz.chapter.number %>
            <% if answer.quiz.get_sort_by_user(current_user) %>
              <span style="color:rgba(180, 180, 180, 0.8);">
                (<%= answer.quiz.get_sort_by_user(current_user) %>)
              </span>
            <% end %>
          <% end %>
        </td>
        <td>
          <%= link_to(quiz_path(answer.quiz)) do %>
            <span style="color:rgba(0, 0, 0, 0.8);">
              <%= answer.quiz.title %>
            </span>
          <% end %>
        </td>
        <td>
          <% if can?(:create, Judgement) %>
            <%= link_to(new_judgement_path(target: answer.id)) do%>
              <%= puts_answer_label(answer) %>
            <% end %>
          <% else %>
            <%= puts_answer_label(answer) %>
          <% end %>
        </td>
        <td>
          <% if answer.created_at > 7.day.ago %>
            <%= distance_of_time_in_words_to_now(answer.created_at) %> ago
          <% else %>
            <%= time_tag(answer.created_at) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="ui column centered grid" style="margin-top:1em;">
  <%= paginate(@answers, window: 2, outer_window: 1) %>
</div>

app/views/answers/new.html.erb
<h2 class="ui dividing header">New answer</h2>

<h5 class="ui top attached blue header"><%= @answer.quiz.chapter.number %>: <%= @answer.quiz.title %></h5>
<div class="ui attached segment">
  <%= markdown_render(@answer.quiz.content) %>
</div>
<% if @preview %>
  <h5 class="ui top attached orange header">Preview</h5>
  <div class="ui attached segment">
    <%= markdown_render(@answer.content) %>
  </div>
  <div style="margin-bottom: 1em;"></div>
<% end %>

<h3 class="ui horizontal header divider">New Answer</h3>

<% if @answer&.quiz&.is_answer_repeat_by_user(current_user.id) %>
  <p> You have already passed this quiz or your submit still being judgement. </p>
<% else %>
  <%= render('form') %>
<% end %>

app/views/answers/show.html.erb
<h2 class="ui dividing header">
  Answer #<%= @answer.id %>
  <%= puts_answer_label(@answer)%>
</h2>


<div>
  <h5 class="ui blue top attached header">
    <%= @answer.quiz.chapter.number %> - <%= @answer.quiz.title %>
  </h5>
  <div class="ui bottom attached segment">
    <%= markdown_render(@answer.quiz.content) %>
  </div>

  <% if can?(:create, Judgement) %>
    <h5 class="ui green top attached header">
      Reference
    </h5>
    <div class="ui bottom attached segment">
      <%= markdown_render(@answer.quiz.reference) %>
    </div>
  <% end %>

  <h5 class="ui orange top attached header">
    Answer
  </h5>
  <div class="ui bottom attached segment">
    <% if params[:ans_format] == 'text' %>
      <code style="color: black; font-size: 1em; background-color: white;">
        <%= simple_format(@answer.content )%>
      </code>
    <% else %>
      <%= markdown_render(@answer.content )%>
    <% end %>
    <p style="text-align:right;">
      ——
      <%= @answer.user.realname %>
      (<%= @answer.user.username %>)
    </p>
  </div>

  <% if params[:ans_format] == 'text' %>
    <%= link_to url_for(target: params[:target]) do %>
      <div class="fluid ui yellow basic button">Change answer render to Markdown</div>
    <% end %>
  <% else %>
    <%= link_to url_for(target: params[:target] ,ans_format: 'text') do %>
      <div class="fluid ui yellow basic button">Change answer render to Text</div>
    <% end %>
  <% end %>
</div>

<div class="ui hidden divider"></div>

<% if can?(:create, Judgement) %>
  <%= link_to(new_judgement_path(target: @answer.id)) do %>
    <div class="ui blue button">Judge</div>
  <% end %>
<% end %>
<% if can?(:update, @answer) %>
  <%= link_to(edit_answer_path(@answer)) do %>
    <div class="ui orange button">Edit</div>
  <% end %>
<% end %>
<% if can?(:destroy, @answer) %>
  <%= link_to(@answer.quiz, method: :delete, data: { confirm: 'Are you sure?' }) do%>
    <div class="ui button">Destroy</div>
  <% end %>
<% end %>
<% if can?(:create, Answer) %>
  <%= link_to(chapter_path(@answer.quiz.chapter)) do %>
    <div class="ui basic button">Back to chapter</div>
  <% end %>
<% end %>
<%= link_to(answers_path) do %>
  <div class="ui basic button">Back to answers</div>
<% end %>