config/routes.rb
Rails.application.routes.draw do

  root(to: "home#index")

  get('score', to: 'score#index')

  devise_for(:users, path_prefix: 'p')
  as(:user) do
    get('p/users/edit' => 'devise/registrations#edit', as: 'edit_user_registration')
    put('p/users' => 'devise/registrations#update', as: 'user_registration')
  end

  concern(:paginatable) do
    get('(page/:page)', action: :index, on: :collection, as: '')
  end

  resources(:users, concerns: :paginatable)
  resources(:judgements, concerns: :paginatable)
  resources(:answers, concerns: :paginatable)
  resources(:quizzes, concerns: :paginatable)
  resources(:chapters, concerns: :paginatable)

end

app/models/answer.rb
class Answer < ActiveRecord::Base

  # Relationship
  belongs_to(:quiz)
  belongs_to(:user)
  has_one(:judgement)

  # Enum
  enum(status: [:queue, :judging, :done])

  # 檢查指定欄位不為 nil 或空字串
  validates_presence_of(:content, :user_id)

  # HasScope Gem: resources filter
  # Ref: https://github.com/plataformatec/has_scope
  scope(:chapter, -> chapter { joins(:quiz).where(quizzes: {chapter_id: chapter}) })
  scope(:quiz, -> quiz { where(quiz_id: quiz) })
  scope(:examinee, -> examinee { where(user_id: examinee) })
  scope(:status, -> status { where(status: status) })
  scope(:period_from, -> period_from { where("? <= created_at ", period_from) })
  scope(:period_end, -> period_end { where("created_at <= ?", period_end) })
  scope(:answer, -> key_word { search_answer(key_word) })

  # 助教觀看答題清單的優先順序演算法
  # 1. 沒通過該章節的優先於通過該章節的
  # 2. 當天提交次數少得優先於提交次數多的
  # 3. 先提交的優先於晚提交的
  def self.judge_piority
    select("answers.*, grids.status as grid_status, counter.count")
    .joins(:quiz, user: :grids)
    .joins("LEFT OUTER JOIN (" +
           " SELECT `user_id`, COUNT(user_id) as `count` FROM `answers`" +
           " WHERE `status` = 2 AND `created_at` >= '#{Time.now.beginning_of_day.getutc}'" +
           " GROUP BY `user_id`) as `counter`" +
           " ON `answers`.`user_id` = `counter`.`user_id`") # Need to refactor with activerecord
    .where("grids.chapter_id = quizzes.chapter_id")
    .order("grid_status ASC") # Not pass is higher than passed
    .order("count ASC")       # Judged answer less one is higher than more one (MYSQL only)
    .order("created_at ASC")  # Ealier submit is higher than later one
  end

  # 萃取今天提交的答案
  def self.today
    where("answers.created_at >= ?", Time.zone.now.beginning_of_day)
  end

  def get_answers_history
    quiz.get_answer_logs_by_user(user_id)
  end
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base

  # Relationship
  has_many(:quizzes)
  has_many(:grids)

  # Enum
  enum(status: [ :inactive, :active ])

  def get_grids_by_user(user)
    nine_grid = self.grids.where(user: user).first
    unless nine_grid
      nine_grid = Grid.new( user:user, chapter: self)
      nine_grid.set_quizzes_random
    end

    nine_grid
  end

  # 本章節已通過的使用者數量
  def get_pass_people_count
    self.grids.where(status: :pass).count
  end

  # 挑戰本章節的使用者數量
  def get_all_people_count
    Grid.where(chapter_id: self.id).count
  end

  # 本章節已通過的使用者比例
  def get_pass_people_rate
    get_pass_people_count.to_f / get_all_people_count.to_f * 100.0
  end

  # 本章節提交還在佇列中的數量
  def get_queue_count
    Answer.joins(:quiz).where(status: [0,1], quizzes: {chapter_id: self.id}).count
  end

  # 本章節提交被審定為通過的數量
  def get_pass_submit_count
    Judgement.joins(answer: :quiz).where(result: 1, quizzes: {chapter_id: self.id}).count
  end

  # 本章節提交被審定為駁回的數量
  def get_reject_submit_count
    Judgement.joins(answer: :quiz).where(result: 0, quizzes: {chapter_id: self.id}).count
  end

  # 本章節所有提交的數量
  def get_all_submit_count
    Answer.joins(:quiz).where(quizzes: {chapter_id: self.id}).count
  end

  # 本章節擁有題目的數量
  def get_all_quizzes_count
    Quiz.where(chapter_id: self.id).count
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController

  # 在指定的方法執行前，先設置相關的實例變數，以省略冗贅的敘述
  before_action(:set_chapter, only: [:show, :edit, :update, :destroy])

  # Authorizing controller actions
  # Ref: https://github.com/ryanb/cancan/wiki/authorizing-controller-actions
  authorize_resource

  # GET /chapters
  def index
    @chapters = Chapter.all.page(params[:page]).per(50)
  end

  # GET /chapters/1
  def show
    if can?(:create, Answer)
      grids = @chapter.get_grids_by_user(current_user)
      @quizzes = grids.get_quizzes
      @quiz_status = grids.get_quizzes_status
    end
  end

  # GET /chapters/new
  def new
    @chapter = Chapter.new
  end

  # GET /chapters/1/edit
  def edit
  end

  # POST /chapters
  def create
    @chapter = Chapter.new(chapter_params)
    if @chapter.save
      redirect_to(@chapter, notice: 'Chapter was successfully created.')
    else
      render(:new)
    end
  end

  # PATCH/PUT /chapters/1
  def update
    if params[:button] && params[:button] == :reset_grids.to_s
      reset_chapter_grids(@chapter.id)
      return redirect_to(@chapter, notice: 'Grids of chapter was successfully reset.')
    end

    if params[:button] && params[:button] == :reload_status.to_s
      reload_chapter_status(@chapter.id)
      return redirect_to(@chapter, notice: 'All of students\' chapter passing status are reloaded.')
    end

    if @chapter.update(chapter_params)
      return redirect_to(@chapter, notice: 'Chapter was successfully updated.')
    end

    render(:edit)

  end

  # DELETE /chapters/1
  def destroy
    @chapter.destroy
    redirect_to(chapters_url, notice: 'Chapter was successfully destroyed.')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_chapter
    @chapter = Chapter.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def chapter_params
    params.require(:chapter).permit(:number, :title, :description, :weight, :status)
  end

  # Reset no passed quizzes of no passed user's grids of the chapter
  def reset_chapter_grids(chapter_id)
    failed_grids = Grid.where(chapter_id: chapter_id, status: Grid.statuses[:fail])
    failed_grids.each do |grids|
      grids.reset_user_grids
    end
  end

  # Reload chapter passing status of all student
  def reload_chapter_status(chapter_id)
    Grid.where(chapter_id: chapter_id).each do | grid |
      grid.update_status
    end
  end

  # 取得章節的統計數據
  helper_method def get_chapter_statistics
    {
      pass_people: {value: @chapter.get_pass_people_count, color: "blue"},
      challengers: {value: @chapter.get_all_people_count, color: "blue"},
      queue: {value: @chapter.get_queue_count, color: "yellow"},
      pass: {value: @chapter.get_pass_submit_count, color: "green"},
      reject: {value: @chapter.get_reject_submit_count, color: "red"},
      submits: {value: @chapter.get_all_submit_count, color: "purple"},
      quizzes: {value: @chapter.get_all_quizzes_count},
    }
  end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_form.html.erb
<%= form_for(@chapter, html: { class: "ui form" }) do |f| %>
  <% if @chapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

      <ul>
      <% @chapter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label(:number) %>
    <%= f.text_field(:number) %>
  </div>
  <div class="field">
    <%= f.label(:title) %>
    <%= f.text_field(:title) %>
  </div>
  <div class="field">
    <%= f.label(:description) %>
    <%= f.text_area(:description) %>
  </div>
  <div class="field">
    <%= f.label(:weight) %>
    <%= f.number_field(:weight) %>
  </div>
  <div class="grouped fields">
    <%= f.label(:status) %>
    <div class="field">
      <div class="ui radio checkbox">
        <%= f.radio_button(:status, :inactive) %>
        <%= f.label(:status, :inactive, value: :inactive) %>
      </div>
    </div>
    <div class="field">
      <div class="ui radio checkbox">
        <%= f.radio_button(:status, :active) %>
        <%= f.label(:status, :active, value: :active) %>
      </div>
    </div>
  </div>
  <div class="field">
    Editor have supported
    <a href="http://markdown.tw/" target="_blank">Markdown markup</a>
    and most of
    <a href="https://help.github.com/articles/github-flavored-markdown/" target="_blank">GitHub Flavored Markdown</a>.
    Try to use it! =D
  </div>
  <%= f.button(class: "ui blue button")%>
<% end %>

app/views/chapters/_grids.html.erb
<h3>Quizzes Bingo Grids</h3>

<p>
  Chose quiz and try to answer. After your correct-answer could be a line, you pass this chapter.
</p>
<table class="nine-grids">
  <tbody>
  <% @quizzes.each_with_index do |quiz, index| %>
    <%= cycle("<tr>", "", "", name: "begin").html_safe %>
      <td class="<%= @quiz_status[index] %>">
        <%= link_to(index+1, quiz_path(quiz)) %>
      </td>
    <%= cycle("", "", "</tr>", name: "end").html_safe %>
  <% end %>
  </tbody>
</table>
<div class="ui list">
  <div class="item" style="color: #5bbd72;">Green means the question is pass.</div>
  <div class="item" style="color: #bba624;">Yello means the question is queue or judgement.</div>
  <div class="item" style="color: #d95c5c;">Red means the question is reject or never answer it. Then, you can answer it.</div>
</div>

app/views/chapters/_quizzes.html.erb
<h3 class="ui dividing header">Listing quizzes</h3>

<table class="ui table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th style="width: 50px;">Assign</th>
      <th style="width: 50px;">Passed</th>
      <th>Pass Rate</th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= link_to(quiz.id, quiz) %></td>
        <td><%= link_to(quiz.title, quiz, style: "color:rgba(0, 0, 0, 0.8);") %></td>
        <td><%= quiz.get_all_assignee_count %></td>
        <td><%= quiz.get_passed_submits_count %></td>
        <td>
          <% if quiz.get_all_assignee_count == 0 %>
            -
          <% else %>
            <div class="ui indicating small progress <%= quiz.get_passed_assignee_rate.round(0) < 100 ? "active" : "success" %>" style="margin: 0;">
              <div class="bar" style="width: <%= quiz.get_passed_assignee_rate.round(0) %>%;">
                <div class="progress">
                  <%= quiz.get_passed_assignee_rate.round(0) %>%
                </div>
              </div>
            </div>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to(new_quiz_path(chapter: @chapter.number)) do %>
  <div class="ui blue button">New Quiz</div>
<% end %>

app/views/chapters/edit.html.erb
<h2 class="ui dividing header">Editing chapter</h2>

<%= render('form') %>

app/views/chapters/index.html.erb
<h2 class="ui dividing header">Listing chapters</h2>

<table class="ui table">
  <thead>
    <tr>
      <th>Number</th>
      <th>Title</th>
    <% if can?(:create, Answer) && cannot?(:manage, @chapter) %>
      <th>Is Passed</th>
    <% end %>
    <% if can?(:manage, Chapter) %>
      <th>Weight</th>
      <th>Activity</th>
      <th colspan="3"></th>
    <% end %>
    </tr>
  </thead>

  <tbody>
    <% @chapters.order("weight").each do |chapter| %>
      <tr>
        <td><%= chapter.number %></td>
        <td>
        <% if chapter.active? %>
          <%= link_to(chapter.title, chapter) %>
        <% else %>
          <%= chapter.title %>
        <% end %>
        </td>
      <% if can?(:create, Answer) && cannot?(:manage, @chapter) %>
        <td>
          <% if chapter.grids.exists?(user: current_user) %>
            <% if chapter.grids.find_by(user: current_user).pass? %>
              <a class="ui green label">Pass</a>
            <% else %>
              <a class="ui red label">Not Pass</a>
            <% end %>
          <% end %>
        </td>
      <% end %>
      <% if can?(:manage, chapter) %>
        <td><%= chapter.weight %></td>
        <td>
          <% if chapter.active? %>
            <a class="ui green label">Active</a>
          <% else %>
            <a class="ui label">Inactive</a>
          <% end %>
        </td>
        <td><%= link_to('Show', chapter) %></td>
        <td><%= link_to('Edit', edit_chapter_path(chapter)) %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="ui column centered grid" style="margin-top:1em;">
  <%= paginate(@chapters, window: 2, outer_window: 1) %>
</div>
<% if can?(:create, Chapter) %>
  <%= link_to(new_chapter_path) do %>
    <div class="ui blue button" style="margin-top:1em;">New Chapter</div>
  <% end %>
<% end %>

app/views/chapters/new.html.erb
<h2 class="ui dividing header">New chapter</h2>

<%= render('form') %>

app/views/chapters/show.html.erb
<h2 class="ui dividing header"><%= @chapter.number %> - <%= @chapter.title %></h2>
<p id="notice"><%= notice %></p>


<h5 class="ui top attached blue header">
  Description
</h5>
<div class="ui attached segment">
  <%= markdown_render(@chapter.description) %>
</div>

<% if can?(:manage, Chapter) %>
  <h5 class="ui attached orange header">
    Properties
  </h5>
  <div class="ui attached segment">
    <div class="ui divided horizontal list">
      <div class="item"> Weight: <%= @chapter.weight %></div>
      <div class="item"><%= @chapter.status.capitalize %></div>
    </div>
  </div>
<% end %>

<h5 class="ui attached teal header">
  Statistics
</h5>
<div class="ui attached segment" style="margin-bottom: 1em;">
  <% if can?(:manage, Chapter) %>
    <div class="ui small statistics">
      <% get_chapter_statistics.each do | index, properties | %>
        <div class="<%= properties[:color] %> statistic" style="margin-bottom: 1em;">
          <div class="value">
            <%= properties[:value] %>
          </div>
          <div class="label">
            <%= "#{index}".humanize.upcase %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="ui indicating progress <%= @chapter.get_pass_people_rate < 100 ? "active" : "success" %>">
    <div class="bar" style="width: <%=@chapter.get_pass_people_rate%>%;">
    </div>
    <div class="label"><%=@chapter.get_pass_people_rate.round(2)%>% Done</div>
  </div>
</div>


<% if can?(:update, Chapter) %>
  <%= link_to(edit_chapter_path(@chapter)) do %>
    <div class="ui blue button">Edit</div>
  <% end %>
<% end %>
<% if can?(:update, Chapter) %>
  <%= form_for(@chapter, html: { class: "ui form", style: "display: inline;" }) do |f| %>
    <%= f.hidden_field(:reset_grids, value: true) %>
    <%= f.button("Reset Grids", value: 'reset_grids', class: "ui red button", data: { confirm: "It will reset grids of no passing quiz. \nAre you sure?" }) %>
  <% end %>
  <%= form_for(@chapter, html: { class: "ui form", style: "display: inline;" }) do |f| %>
    <%= f.hidden_field(:reset_grids, value: true) %>
    <%= f.button("Reload status", value: 'reload_status', class: "ui orange button", data: { confirm: "It will All of students' chapter passing status. Are you sure?" }) %>
  <% end %>
<% end %>
<% if can?(:destroy, @chapter) %>
  <%= link_to(@chapter, method: :delete, data: { confirm: 'Are you sure?' }) do%>
    <div class="ui button">Destroy</div>
  <% end %>
<% end %>
<%= link_to(chapters_path) do %>
  <div class="ui basic button">Back to chapters</div>
<% end %>

<% if can?(:manage, Quiz) %>
  <%= render('quizzes', locals: {quizzes:  @chapter.quizzes}) %>
<% elsif can?(:create, Answer) %>
  <%= render('grids') %>
<% end %>