config/routes.rb
Rails.application.routes.draw do

  root(to: "home#index")

  get('score', to: 'score#index')

  devise_for(:users, path_prefix: 'p')
  as(:user) do
    get('p/users/edit' => 'devise/registrations#edit', as: 'edit_user_registration')
    put('p/users' => 'devise/registrations#update', as: 'user_registration')
  end

  concern(:paginatable) do
    get('(page/:page)', action: :index, on: :collection, as: '')
  end

  resources(:users, concerns: :paginatable)
  resources(:judgements, concerns: :paginatable)
  resources(:answers, concerns: :paginatable)
  resources(:quizzes, concerns: :paginatable)
  resources(:chapters, concerns: :paginatable)

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nine Grids</title>
  <%= stylesheet_link_tag('application', media: 'all', 'data-turbolinks-track' => true) %>
  <%= javascript_include_tag('application', 'data-turbolinks-track' => true) %>
  <%= csrf_meta_tags %>
</head>
<body id="main">
  <nav class="ui secondary pointing menu">
    <%= link_to(root_path, :class => 'item') do %>
      <i class="home icon"></i> Home
    <% end %>
    <% if can?(:read, User) %>
      <%= link_to(users_path, :class => 'item') do %>
        <i class="users icon"></i> User
      <% end %>
    <% end %>
    <% if can?(:read, Chapter) %>
      <%= link_to(chapters_path, :class => 'item') do %>
        <i class="list icon"></i> Chapters
      <% end %>
    <% end %>
    <% if can?(:manage, Quiz) %>
      <%= link_to(quizzes_path, :class => 'item') do %>
        <i class="file text icon"></i> Quizzes
      <% end %>
    <% end %>
    <% if can?(:read, Answer) %>
      <%= link_to(answers_path, :class => 'item') do %>
        <i class="idea icon"></i> Answers
      <% end %>
    <% end %>
    <% if can?(:read, Judgement) %>
      <%= link_to(judgements_path, :class => 'item') do %>
        <i class="checkmark box icon"></i> Judgements
      <% end %>
    <% end %>
    <% if can?(:read, Judgement) %>
      <%= link_to(score_path, :class => 'item') do %>
        <i class="checkmark box icon"></i> Score
      <% end %>
    <% end %>
    <div class="right menu">
      <% if user_signed_in? %>
        <%= link_to(destroy_user_session_path, :method => :delete, :class => 'item') do %>
          <i class="sign out icon"></i> Sign out
        <% end %>
      <% else %>
        <%= link_to(new_user_session_path, :class => 'item') do %>
          <i class="sign in icon"></i> Sign in
        <% end %>
      <% end %>
    </div>
  </nav>

  <% if !notice.nil? %>
    <div class="ui positive message">
      <p><%= notice %></p>
    </div>
  <% end %>
  <% if !alert.nil? %>
    <div class="ui negative message">
      <p><%= alert %></p>
    </div>
  <% end %>

  <div class="container">
    <%= yield %>
    <div class="push"></div>
  </div>

  <footer class="main footer">
    <div class="ui divider"></div>

    <div class="ui divided horizontal footer link list">
      <div class="item">
        Nine Grids Judge System
      </div>
      <div class="item">
        <a href="https://www.facebook.com/NCUCompiler" target="_blank">Compiler-A NCU </a>
      </div>
      <div class="item">
        Developed by
        <a href="http://fntsr.tw">fntsrlike</a>
      </div>
    </div>
  </footer>
</body>
</html>